Fix change in RestChannel
`RestChannel` now has a parameter `detailedErrorsEnabled` which wasn't being passed in, causing a `NoSuchMethodError` if you try to run it with elasticsearch 1.5 (and a compile error if you tried to compile it).

See also https://github.com/elastic/elasticsearch/pull/10117

Closes #30.
(cherry picked from commit 91445ef)
(cherry picked from commit 849a457)